apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "prober-operator.labels" . | nindent 4 }}
  name: {{ .Release.Name }}-controller-manager-metrics-service
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
  selector:
    control-plane: controller-manager